/* Dependency-free, file://-compatible dashboard. Aggregate data is generated by Python. */
(() => {
  'use strict';
  const data = window.OLIST_DATA;
  if (!data) { document.body.insertAdjacentHTML('afterbegin', '<p>Run the analysis pipeline to create dashboard/data.js.</p>'); return; }
  const $ = id => document.getElementById(id);
  const fmt = n => Number(n || 0).toLocaleString('en-US');
  const brl = n => 'R$ ' + Number(n || 0).toLocaleString('en-US', {maximumFractionDigits:0});
  const pct = n => (100 * Number(n || 0)).toFixed(1) + '%';
  const known = r => !['unknown','missing'].includes(r.origin);
  const label = s => s.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  const safe = v => Math.max(0, Number.isFinite(v) ? v : 0);

  $('kpi-leads').textContent = fmt(data.overview.eligible_leads_90d);
  $('kpi-conv').textContent = pct(data.overview.overall_conversion_90d);
  $('kpi-wins').textContent = `${fmt(data.overview.won_leads_90d)} qualified leads`;
  $('kpi-sellers').textContent = fmt(data.overview.matured_seller_wins);
  $('kpi-gmv').textContent = brl(data.overview.recorded_seller_gmv_90d_brl);

  const filter = $('origin-filter');
  data.leads.filter(known).sort((a,b) => b.eligible_leads - a.eligible_leads)
    .forEach(r => { const option = document.createElement('option'); option.value = r.origin; option.textContent = label(r.origin); filter.append(option); });

  function drawBars() {
    const rows = [...data.leads].sort((a,b) => b.eligible_leads - a.eligible_leads);
    const max = Math.max(...rows.map(r => r.ci_high));
    const chart = $('conversion-chart'); chart.replaceChildren();
    for (const r of rows) {
      const el = document.createElement('div');
      el.className = 'bar-row' + (!known(r) ? ' is-unknown' : '') + (filter.value === r.origin ? ' is-selected' : '');
      const name = document.createElement('span'); name.className='name'; name.textContent=label(r.origin); name.title=`${fmt(r.eligible_leads)} qualified leads`;
      const area=document.createElement('span'); area.className='bar-area';
      const fill=document.createElement('i'); fill.className='bar-fill'; fill.style.width=`${100*r.conversion_90d/max}%`;
      const interval=document.createElement('i'); interval.className='ci'; interval.style.left=`${100*r.ci_low/max}%`; interval.style.width=`${100*(r.ci_high-r.ci_low)/max}%`;
      area.append(fill,interval);
      const rate=document.createElement('span'); rate.className='percent'; rate.textContent=pct(r.conversion_90d);
      el.append(name,area,rate); chart.append(el);
    }
  }

  function selected() {
    if (filter.value !== 'traceable') {
      return {leads:data.leads.find(r => r.origin===filter.value), sellers:data.sellers.find(r=>r.origin===filter.value)};
    }
    const leadRows=data.leads.filter(known), sellerRows=data.sellers.filter(known);
    const leadCount=leadRows.reduce((x,r)=>x+r.eligible_leads,0), wins=leadRows.reduce((x,r)=>x+r.wins_90d,0);
    const sellerCount=sellerRows.reduce((x,r)=>x+r.matured_wins,0), activated=sellerRows.reduce((x,r)=>x+r.wins_with_recorded_sales,0);
    const gmv=sellerRows.reduce((x,r)=>x+r.observed_gmv_90d_brl,0);
    return {leads:{origin:'traceable',eligible_leads:leadCount,wins_90d:wins,conversion_90d:wins/leadCount},
      sellers:{origin:'traceable',matured_wins:sellerCount,wins_with_recorded_sales:activated,
               mean_gmv_per_win_brl:gmv/sellerCount,observed_sale_share:activated/sellerCount}};
  }

  function drawLine() {
    const months=[...new Set(data.monthly.map(r=>r.month))].sort();
    const values=months.map(m=>data.monthly.filter(r=>r.month===m && (filter.value==='traceable' ? known(r) : r.origin===filter.value))
       .reduce((sum,r)=>sum+r.observed_gmv_brl,0));
    const max=Math.max(100,...values); const height=155, bottom=175, left=35, width=640;
    const positions=values.map((v,i)=>[left+i*(width/(Math.max(1,values.length-1))),bottom-(v/max)*height]);
    const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');
    svg.setAttribute('viewBox','0 0 700 220'); svg.setAttribute('aria-label','Recorded monthly seller GMV in BRL');
    const make=(tag,attrs)=>{const node=document.createElementNS(svg.namespaceURI,tag);for(const [k,v] of Object.entries(attrs))node.setAttribute(k,v);svg.append(node);return node;};
    for(let j=0;j<3;j++){const y=bottom-j*height/2;make('line',{x1:left,y1:y,x2:675,y2:y,stroke:'#e1e9df','stroke-width':'1'});
       const t=make('text',{x:'0',y:y+4});t.textContent=(j*max/2>=1000?(j*max/2000).toFixed(0)+'k':Math.round(j*max/2));}
    if(positions.length){make('polyline',{points:positions.map(p=>p.join(',')).join(' '),fill:'none',stroke:'#206d65','stroke-width':'3','stroke-linejoin':'round'});
      positions.forEach(p=>make('circle',{cx:p[0],cy:p[1],r:'3',fill:'#d98965'}));}
    months.forEach((m,i)=>{if(i%Math.max(1,Math.ceil(months.length/7))!==0 && i!==months.length-1)return;
      const t=make('text',{x:positions[i][0],y:'204','text-anchor':'middle'});t.textContent=m.slice(2);});
    $('monthly-chart').replaceChildren(svg);
  }

  function update() {
    drawBars(); drawLine(); const {leads,sellers}=selected();
    const sample=sellers.matured_wins||0;
    $('yield-value').textContent=brl(sellers.mean_gmv_per_win_brl);
    $('activation-value').textContent=pct(sellers.observed_sale_share);
    $('activation-track').style.width=`${100*(sellers.observed_sale_share||0)}%`;
    $('yield-interval').textContent=filter.value==='traceable' ? 'Known-source aggregate; see channel-specific intervals in CSV export.'
      : `Bootstrap 95% interval: ${brl(sellers.gmv_ci_low_brl)} – ${brl(sellers.gmv_ci_high_brl)}`;
    $('yield-note').textContent=`${fmt(sample)} sellers won within 90 days of first contact, then observed for a full 90-day order window. Value includes zeros, excludes freight.`;
    $('activation-note').textContent=`${fmt(sellers.wins_with_recorded_sales)} sellers with ≥1 recorded delivered order within 90 days.`;
    const small=sample<30;
    $('scenario-warning').textContent=small ? `Only ${sample} fully observed seller wins for this source. Scenario estimates are unstable; choose a larger channel.`
       : filter.value==='traceable' ? 'All known sources pooled. Channel mix and seller characteristics may change in a real campaign.'
       : 'Channel relationships are descriptive. Changing spend or conversion may change the mix of sellers.';
    const n=safe(+$('assumed-leads').value), uplift=Number($('assumed-uplift').value)||0;
    const fee=safe(+$('assumed-fee').value)/100, cost=safe(+$('assumed-cost').value);
    const adjusted=Math.max(0,Math.min(1,leads.conversion_90d+uplift/100));
    const wins=n*adjusted; const feeRevenue=wins*sellers.mean_gmv_per_win_brl*fee;
    $('result-wins').textContent=small ? 'Insufficient cohort' : fmt(Math.round(wins));
    $('result-fees').textContent=small ? 'Insufficient cohort' : brl(feeRevenue);
    $('result-net').textContent=small ? 'Insufficient cohort' : brl(feeRevenue-cost);
  }
  filter.addEventListener('change',update);
  ['assumed-leads','assumed-uplift','assumed-fee','assumed-cost'].forEach(id=>$(id).addEventListener('input',update));
  update();
})();
